/*
 * Copyright 2025-2026 Mehr Guard Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.raouf.mehrguard.platform

import android.os.Build

/**
 * Android implementation of Platform.
 */
actual class Platform actual constructor() {
    actual val name: String = "Android"
    actual val version: String = Build.VERSION.SDK_INT.toString()
    actual val hasCamera: Boolean = true
    actual val hasHaptics: Boolean = true
    actual val hasLocalStorage: Boolean = true
    actual val isDebug: Boolean = BuildConfig.DEBUG
}

actual fun getPlatform(): Platform = Platform()

/**
 * Access to BuildConfig for debug detection.
 * This will be generated by the Android build system.
 */
private object BuildConfig {
    val DEBUG: Boolean = try {
        Class.forName("com.raouf.mehrguard.android.BuildConfig")
            .getField("DEBUG")
            .getBoolean(null)
    } catch (e: Exception) {
        false
    }
}
