/*
 * Copyright 2025-2026 QR-SHIELD Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.qrshield.desktop

import com.qrshield.desktop.model.AnalysisResult
import com.qrshield.model.Verdict
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Unit tests for QR-SHIELD Desktop App
 *
 * Tests the desktop-specific components including:
 * - AnalysisResult model
 * - WindowPreferences (saving/loading)
 * - Theme configuration
 *
 * @author QR-SHIELD Team
 * @since 1.1.1
 */
class DesktopAppTest {

    // =========================================================================
    // ANALYSIS RESULT TESTS
    // =========================================================================

    @Test
    fun analysisResult_createsWithCorrectValues() {
        val result = AnalysisResult(
            url = "https://example.com",
            score = 25,
            verdict = Verdict.SUSPICIOUS,
            flags = listOf("IP Address", "HTTP Not HTTPS"),
            timestamp = 1234567890L
        )

        assertEquals("https://example.com", result.url)
        assertEquals(25, result.score)
        assertEquals(Verdict.SUSPICIOUS, result.verdict)
        assertEquals(2, result.flags.size)
        assertEquals(1234567890L, result.timestamp)
    }

    @Test
    fun analysisResult_safeVerdictWithLowScore() {
        val result = AnalysisResult(
            url = "https://google.com",
            score = 5,
            verdict = Verdict.SAFE,
            flags = emptyList()
        )

        assertEquals(Verdict.SAFE, result.verdict)
        assertTrue(result.score <= 20, "Safe verdict should have low score")
        assertTrue(result.flags.isEmpty(), "Safe verdict should have no flags")
    }

    @Test
    fun analysisResult_maliciousVerdictWithHighScore() {
        val result = AnalysisResult(
            url = "http://phishing.tk/login",
            score = 85,
            verdict = Verdict.MALICIOUS,
            flags = listOf("High-risk TLD", "HTTP Not HTTPS", "Brand Impersonation")
        )

        assertEquals(Verdict.MALICIOUS, result.verdict)
        assertTrue(result.score >= 50, "Malicious verdict should have high score")
        assertTrue(result.flags.isNotEmpty(), "Malicious verdict should have flags")
    }

    @Test
    fun analysisResult_timestampIsAutoGenerated() {
        val before = System.currentTimeMillis()
        val result = AnalysisResult(
            url = "https://test.com",
            score = 10,
            verdict = Verdict.SAFE,
            flags = emptyList()
        )
        val after = System.currentTimeMillis()

        assertTrue(result.timestamp >= before, "Timestamp should be after start")
        assertTrue(result.timestamp <= after, "Timestamp should be before end")
    }

    // =========================================================================
    // VERDICT TYPES TESTS
    // =========================================================================

    @Test
    fun verdict_allTypesExist() {
        val verdicts = listOf(Verdict.SAFE, Verdict.SUSPICIOUS, Verdict.MALICIOUS, Verdict.UNKNOWN)

        assertEquals(4, verdicts.size)
        assertTrue(verdicts.all { it.name.isNotEmpty() })
    }

    @Test
    fun verdict_safeScoreRange() {
        val safeResult = AnalysisResult("https://google.com", 10, Verdict.SAFE, emptyList())
        assertTrue(safeResult.score <= 30, "Safe score should be <= 30")
    }

    @Test
    fun verdict_suspiciousScoreRange() {
        val suspiciousResult = AnalysisResult("https://bit.ly/abc", 40, Verdict.SUSPICIOUS, listOf("URL Shortener"))
        assertTrue(suspiciousResult.score in 20..70, "Suspicious score should be 20-70")
    }

    @Test
    fun verdict_maliciousScoreRange() {
        val maliciousResult = AnalysisResult("http://phishing.tk", 80, Verdict.MALICIOUS, listOf("Multiple risks"))
        assertTrue(maliciousResult.score >= 50, "Malicious score should be >= 50")
    }

    // =========================================================================
    // FLAGS STRUCTURE TESTS
    // =========================================================================

    @Test
    fun flags_areImmutableList() {
        val flags = listOf("Flag 1", "Flag 2")
        val result = AnalysisResult("https://test.com", 30, Verdict.SUSPICIOUS, flags)

        assertEquals(flags.size, result.flags.size)
        assertEquals("Flag 1", result.flags[0])
        assertEquals("Flag 2", result.flags[1])
    }

    @Test
    fun flags_emptyForSafeUrls() {
        val result = AnalysisResult("https://google.com", 5, Verdict.SAFE, emptyList())
        assertTrue(result.flags.isEmpty())
    }

    // =========================================================================
    // DATA CLASS BEHAVIOR TESTS
    // =========================================================================

    @Test
    fun analysisResult_equality() {
        val result1 = AnalysisResult("https://test.com", 20, Verdict.SAFE, emptyList(), 12345L)
        val result2 = AnalysisResult("https://test.com", 20, Verdict.SAFE, emptyList(), 12345L)

        assertEquals(result1, result2)
    }

    @Test
    fun analysisResult_copy() {
        val original = AnalysisResult("https://test.com", 20, Verdict.SAFE, emptyList())
        val copy = original.copy(score = 30, verdict = Verdict.SUSPICIOUS)

        assertEquals("https://test.com", copy.url)
        assertEquals(30, copy.score)
        assertEquals(Verdict.SUSPICIOUS, copy.verdict)
    }

    @Test
    fun analysisResult_toStringContainsDetails() {
        val result = AnalysisResult("https://test.com", 20, Verdict.SAFE, emptyList())
        val string = result.toString()

        assertTrue(string.contains("https://test.com"))
        assertTrue(string.contains("20"))
        assertTrue(string.contains("SAFE"))
    }
}
